# Generated by Django 2.2.6 on 2019-10-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
