# Generated by Django 2.2.6 on 2019-10-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testStore', '0002_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
