# Generated by Django 2.2.6 on 2019-10-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testStore', '0003_auto_20191015_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
